#pragma once

#define WM_CUSTOM_MESSAGE (WM_APP + 1)
#define WM_BOT_PLAY_MESSAGE (WM_APP + 2)

namespace Utils
{
	enum GameEvents { CARD1_PICKED, CARD1_PICKED_HIDDEN, CARD2_PICKED, CARD2_PICKED_HIDDEN, CARD3_PICKED, CARD3_PICKED_HIDDEN, 
		TRUCO, CONTINUE, QUIT, TRUCO_FROM_OPPONENT, RUN_FROM_MAO_DE_ONZE, NONE };
}